print('Hola'+' Bryan')
print('Me llamo \"Bryan\"')
print('Esta es una primera linea \n esta es otra linea')
print('Esta es una primera linea \t esta es otra linea')
print('This isn\'t a number ')
print('\\')